# Generated by Django 3.0.6 on 2020-05-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('item_from_other_library', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_alma', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Primary id')),
                ('barcode', models.CharField(max_length=20, verbose_name='Code-barres')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse mail du lecteur')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('user_request_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name=' id')),
                ('item_barcode', models.CharField(max_length=30, verbose_name='Code-barres')),
                ('library_name', models.CharField(max_length=200, verbose_name='Nom de la bibliotheque')),
                ('library_id', models.CharField(max_length=10, verbose_name='Identifiant Alma de la bibliotheque')),
                ('location', models.CharField(max_length=200, verbose_name="Localisation de l'exemplaire")),
                ('call_number', models.CharField(max_length=30, verbose_name="Cote de l'exemplaire")),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description du fascicule (système)')),
                ('manual_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description du fascicule (usager)')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_management.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.Person'),
        ),
    ]
