# Generated by Django 3.0.6 on 2020-05-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_pickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pickuplocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_management.PickupLocation'),
        ),
    ]
