# Generated by Django 3.0.6 on 2020-05-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0003_cart_pickuplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pickuplocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.PickupLocation'),
        ),
    ]
