# Generated by Django 3.0.6 on 2020-06-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0004_auto_20200530_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.AddField(
            model_name='items',
            name='pickuplocation',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='cart_management.PickupLocation'),
            preserve_default=False,
        ),
    ]
