# Generated by Django 3.0.6 on 2020-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0005_auto_20200602_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='call_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Cote de l'exemplaire"),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_barcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='items',
            name='library_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifiant Alma de la bibliotheque'),
        ),
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Localisation de l'exemplaire"),
        ),
    ]
