# Generated by Django 3.0.6 on 2020-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0006_auto_20200602_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
