# Generated by Django 3.0.6 on 2020-06-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0007_items_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='person',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='cart_management.Person'),
            preserve_default=False,
        ),
    ]
