# Generated by Django 3.0.6 on 2020-06-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0010_auto_20200603_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Document réservé', 'verbose_name_plural': 'Documents réservés'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Lecteur', 'verbose_name_plural': 'Lecteurs'},
        ),
        migrations.AlterModelOptions(
            name='pickuplocation',
            options={'verbose_name': 'Bibliothèque de retrait', 'verbose_name_plural': 'Bibliothèques de retrait'},
        ),
    ]
