# Generated by Django 3.1.3 on 2020-11-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0011_auto_20200605_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(verbose_name='Date de retrait des ouvrages'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.pickuplocation', verbose_name='Bibliothèque de retrait'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='cart_management.person', verbose_name='Lecteur'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
