# Generated by Django 3.1.3 on 2020-11-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0012_auto_20201105_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='booked',
        ),
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Commande retirée ?'),
        ),
        migrations.AlterField(
            model_name='items',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.person', verbose_name='Demandeur'),
        ),
        migrations.AlterField(
            model_name='items',
            name='pickuplocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.pickuplocation', verbose_name='Bibliothèque de retrait'),
        ),
        migrations.AlterField(
            model_name='items',
            name='user_request_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Identifiant de la réservation'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='close_hour',
            field=models.IntegerField(default=17, verbose_name='Heure de fermeture du service de retrait'),
        ),
    ]
