# Generated by Django 3.1.3 on 2020-11-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_management', '0014_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.pickuplocation', verbose_name='Bibliothèque')),
                ('staffuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur pro')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
