# Generated by Django 3.1.3 on 2020-11-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0016_auto_20201106_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='done',
            new_name='is_done',
        ),
    ]
