# Generated by Django 3.1.3 on 2020-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0017_auto_20201106_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='opening_days',
            field=models.ManyToManyField(to='cart_management.DaysOfWeek'),
        ),
    ]
