# Generated by Django 3.1.3 on 2020-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0018_auto_20201106_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='day_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
