# Generated by Django 3.1.3 on 2020-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0019_daysofweek_day_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='mid_day_break',
            field=models.BooleanField(default=False, verbose_name='Fermeture méridienne (bibliothèque fermée entre 12h & 14h)'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='handling_time',
            field=models.IntegerField(default=1, verbose_name='Délai en jour pour la préparation de la commande'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='plot_number',
            field=models.IntegerField(default=4, verbose_name='Nombre de plages par heure'),
        ),
    ]
