# Generated by Django 3.1.3 on 2020-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0020_auto_20201107_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='tel',
            field=models.CharField(blank=True, default='00 00 00 00 00', max_length=50, verbose_name='Téléphone'),
        ),
    ]
