# Generated by Django 3.1.3 on 2020-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0021_pickuplocation_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='from_email',
            field=models.EmailField(default='', max_length=254, verbose_name="Adresse à utiliser pour l'envoi du mail au lecteur"),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Adresse vers laquelle envoyer la liste des documents réservés'),
        ),
    ]
