# Generated by Django 3.1.3 on 2020-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0023_auto_20201116_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de fermetures de la bibliothèque')),
            ],
            options={
                'verbose_name': 'Jour',
                'verbose_name_plural': 'Jours de fermetures',
            },
        ),
        migrations.AlterModelOptions(
            name='daysofweek',
            options={'verbose_name': 'Jour', 'verbose_name_plural': "Jours d'ouvertures"},
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='closed_days',
            field=models.ManyToManyField(to='cart_management.ClosedDays'),
        ),
    ]
