# Generated by Django 3.1.3 on 2020-11-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0024_auto_20201116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeddays',
            name='date',
            field=models.DateField(verbose_name='Date de fermetures de la bibliothèque'),
        ),
    ]
