# Generated by Django 3.1.3 on 2020-11-19 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0027_auto_20201116_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 27, 36, 29883), editable=False, verbose_name='Date et heure de création'),
        ),
        migrations.AddField(
            model_name='items',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 27, 36, 29910), verbose_name='Date et heure de modification'),
        ),
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Statut de la réservation'),
        ),
    ]
