# Generated by Django 3.1.3 on 2020-11-19 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0028_auto_20201119_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date et heure de création'),
        ),
        migrations.AlterField(
            model_name='items',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de modification'),
        ),
    ]
